(()=>{'use strict';
const DATA=window.MARKET_DATA,$=id=>document.getElementById(id),canvas=$('gameCanvas'),ctx=canvas.getContext('2d');
const screens={home:$('homeScreen'),game:$('gameScreen'),result:$('resultScreen')};
const MAX_MS=300000,STAGE_MS=2000,STAGES=150,PLAYER_R=7;
const state={market:'nikkei',mode:'beginner',lang:'ja',running:false,started:false,progress:0,prevProgress:0,elapsed:0,lastTs:0,playerY:0,vy:0,pressing:false,cameraLog:null,sound:true,raf:0,eventUntil:0,lastEventKey:'',moveUntil:0,lastMoveKey:'',lastYear:null,trail:[]};
const TXT={ja:{refresh:'更新',nickname:'ランキング名',empty:'まだ記録がありません。',loading:'ランキング読込中…',local:'LOCAL RANKING',global:'GLOBAL RANKING',ended:'RUN ENDED',complete:'RUN COMPLETE',move:'前日比',anon:'名無しトレーダー',market:'市場',date:'年月',index:'指数',level:'難易度',time:'時間',topRunners:'ランキング',beginner:'初心者',advanced:'上級者',nikkei:'日経平均',retry:'もう一度',home:'ホーム'},en:{refresh:'REFRESH',nickname:'RANKING NAME',empty:'No records yet.',loading:'Loading ranking…',local:'LOCAL RANKING',global:'GLOBAL RANKING',ended:'RUN ENDED',complete:'RUN COMPLETE',move:'DAILY MOVE',anon:'Anonymous',market:'MARKET',date:'DATE',index:'INDEX',level:'LEVEL',time:'TIME',topRunners:'TOP RUNNERS',beginner:'BEGINNER',advanced:'ADVANCED',nikkei:'NIKKEI 225',retry:'RETRY',home:'HOME'}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
function t(k){return TXT[state.lang][k]||k}function marketLabel(m=state.market){return state.lang==='ja'?DATA[m].labelJa:DATA[m].labelEn}function modeLabel(m=state.mode){return t(m)}function rankingKey(){return `nikkei-${state.mode}`}function baseSigma(){return state.mode==='beginner'?3:1.5}function effectiveSigma(f=bandFactor()){return baseSigma()*f}
function showScreen(name){Object.entries(screens).forEach(([k,v])=>v.classList.toggle('active',k===name));window.scrollTo({top:0,behavior:'instant'});}function sanitizeName(v){return (v||t('anon')).replace(/[<>\n\r]/g,'').trim().slice(0,14)||t('anon');}
function dateObj(s){const [y,m,d='1']=s.split('-').map(Number);return new Date(Date.UTC(y,m-1,d))}function formatDate(s){if(state.lang==='ja'){const [y,m]=s.split('-');return `${y}年${Number(m)}月`}return dateObj(s).toLocaleDateString('en-US',{year:'numeric',month:'short',timeZone:'UTC'});}function formatFullDate(s){if(state.lang==='ja'){const [y,m,d='1']=s.split('-');return `${y}年${Number(m)}月${Number(d)}日`}return dateObj(s).toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'});}const EVENT_KIND={ja:{politics:'政治',policy:'金融政策',market:'相場',investing:'投資制度',economy:'経済',global:'世界',milestone:'節目'},en:{politics:'POLITICS',policy:'MONETARY POLICY',market:'MARKET',investing:'INVESTING',economy:'ECONOMY',global:'GLOBAL',milestone:'MILESTONE'}};function eventKind(k){return (EVENT_KIND[state.lang]&&EVENT_KIND[state.lang][k])||'';}function eventColor(k,a=.75){const c={politics:`rgba(135,177,255,${a})`,policy:`rgba(255,205,96,${a})`,market:`rgba(255,98,110,${a})`,investing:`rgba(103,243,157,${a})`,economy:`rgba(210,160,255,${a})`,global:`rgba(255,156,92,${a})`,milestone:`rgba(105,220,240,${a})`};return c[k]||`rgba(255,98,110,${a})`;}function formatHUDDate(s){const [y,m]=s.split('-');return state.lang==='ja'?`${y}.${m}`:`${m}/${y}`;}function fmtValue(v,m=state.market){return m==='nikkei'?(state.lang==='ja'?`${Math.round(v).toLocaleString('ja-JP')}円`:`${Math.round(v).toLocaleString('en-US')} JPY`):`${Number(v).toLocaleString('en-US',{maximumFractionDigits:1})} pt`;}function fmtTime(ms){const s=Math.max(0,Math.floor(ms/1000)),m=Math.floor(s/60);return `${String(m).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function stageNo(){return clamp(Math.floor(state.elapsed/STAGE_MS)+1,1,STAGES)}function speedFactor(s=stageNo()){const t=clamp((s-1)/(STAGES-1),0,1),knots=[.65,1.10,1.20,1.35,1.65,2.45],pos=t*(knots.length-1),i=Math.min(knots.length-2,Math.floor(pos)),f=pos-i;return lerp(knots[i],knots[i+1],f)}function bandFactor(s=stageNo()){if(s<=30)return 1-(s-1)*(.20/29);return Math.max(.40,.80-(s-30)*(.40/120))}function baseSpeed(rows){let sum=0;for(let s=1;s<=STAGES;s++)sum+=speedFactor(s)*(STAGE_MS/1000);return (rows.length-1)/sum;}function rowAt(rows,p){const i=Math.floor(p),f=p-i,a=rows[clamp(i,0,rows.length-1)],b=rows[clamp(i+1,0,rows.length-1)],r=[a[0]];for(let k=1;k<a.length;k++)r[k]=lerp(a[k],b[k],f);return r;}function dynBand(row,f=bandFactor()){const mean=row[5],sigma=effectiveSigma(f);return{mean,upper:mean+(row[6]-mean)*sigma,lower:mean+(row[7]-mean)*sigma};}
let audioCtx=null,bgmTimer=0,bgmStep=0,bgmNext=0,bgmBus=null;
function ensureAudio(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}catch{return null}}
function tone(freq,start,dur=.08,type='sine',gain=.02,dest=null){const ac=ensureAudio();if(!ac||!state.sound)return;const o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.setValueAtTime(freq,start);g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(Math.max(.0002,gain),start+.012);g.gain.exponentialRampToValueAtTime(.0001,start+dur);o.connect(g);g.connect(dest||ac.destination);o.start(start);o.stop(start+dur+.02)}
function beep(freq=440,dur=.035,type='sine',gain=.018){const ac=ensureAudio();if(!ac||!state.sound)return;tone(freq,ac.currentTime,dur,type,gain)}
function setupBgmBus(){const ac=ensureAudio();if(!ac)return null;if(!bgmBus){bgmBus=ac.createGain();bgmBus.gain.value=.42;bgmBus.connect(ac.destination)}return bgmBus}
function scheduleBgmStep(step,when){if(!state.sound||!state.running)return;const bus=setupBgmBus();if(!bus)return;const bass=[110,110,146.83,110,164.81,146.83,98,110][step%8];const arp=[220,261.63,329.63,293.66,246.94,293.66,369.99,329.63][step%8];tone(bass,when,.20,'triangle',.018,bus);if(step%2===0)tone(arp,when+.02,.085,'square',.0058,bus);if(stageNo()>=31&&step%4===2)tone(arp*2,when+.03,.055,'sine',.0038,bus)}
function bgmScheduler(){const ac=ensureAudio();if(!ac||!state.sound||!state.running)return;const stepDur=60/132/2;while(bgmNext<ac.currentTime+.42){scheduleBgmStep(bgmStep++,bgmNext);bgmNext+=stepDur}}
function startBgm(){if(!state.sound||!state.running)return;const ac=ensureAudio();if(!ac)return;stopBgm(false);bgmStep=0;bgmNext=ac.currentTime+.03;bgmScheduler();bgmTimer=setInterval(bgmScheduler,110)}
function stopBgm(resetBus=true){if(bgmTimer){clearInterval(bgmTimer);bgmTimer=0}if(resetBus&&bgmBus&&audioCtx){try{bgmBus.gain.cancelScheduledValues(audioCtx.currentTime);bgmBus.gain.setTargetAtTime(.0001,audioCtx.currentTime,.03)}catch{}}if(resetBus)bgmBus=null}
function playHistorySE(kind='market'){const ac=ensureAudio();if(!ac||!state.sound)return;const base={politics:392,policy:523.25,market:293.66,investing:659.25,economy:440,global:349.23,milestone:783.99}[kind]||440;tone(base,ac.currentTime,.10,'sine',.026);tone(base*1.25,ac.currentTime+.075,.12,'triangle',.022);tone(base*1.5,ac.currentTime+.15,.15,'sine',.018)}
function playYearSE(){const ac=ensureAudio();if(!ac||!state.sound)return;[523.25,659.25,783.99].forEach((f,i)=>tone(f,ac.currentTime+i*.055,.095,'square',.014))}

function applyLanguage(){document.documentElement.lang=state.lang;$('langBtn').textContent=state.lang==='ja'?'日本語 / EN':'JA / English';$('soundBtn').textContent=state.sound?'SOUND ON':'SOUND OFF';$('nickname').placeholder=t('nickname');document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$('refreshHomeRanking').textContent=t('refresh');$('refreshResultRanking').textContent=t('refresh');$('retryBtn').textContent=t('retry');$('homeBtn').textContent=t('home');$('moveLabel').textContent=t('move');$('homeRankingTitle').textContent=state.lang==='ja'?`${modeLabel()}ランキング`:`${modeLabel()} RANKING`;if(!state.running){loadRanking(screens.result.classList.contains('active')?'resultRanking':'homeRanking',rankingKey());}drawFrame(0,baseSpeed(DATA.nikkei.rows)*speedFactor());}
$('langBtn').addEventListener('click',()=>{state.lang=state.lang==='ja'?'en':'ja';applyLanguage();});$('soundBtn').addEventListener('click',()=>{state.sound=!state.sound;$('soundBtn').textContent=state.sound?'SOUND ON':'SOUND OFF';if(state.sound){beep(540);if(state.running)startBgm()}else stopBgm();});$('brandBtn').addEventListener('click',()=>{if(!state.running)showScreen('home')});document.querySelectorAll('.market-card').forEach(btn=>btn.addEventListener('click',()=>{state.mode=btn.dataset.mode;document.querySelectorAll('.market-card').forEach(b=>b.classList.toggle('selected',b===btn));beep(380,.025);$('homeRankingTitle').textContent=state.lang==='ja'?`${modeLabel()}ランキング`:`${modeLabel()} RANKING`;loadRanking('homeRanking',rankingKey())}));
function resizeCanvas(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);canvas._w=rect.width;canvas._h=rect.height;if(!state.running)drawFrame(0,1);}window.addEventListener('resize',resizeCanvas);
function mapView(progress,dt=0,instant=false){const rows=DATA[state.market].rows,w=canvas._w||1000,h=canvas._h||620,xStep=clamp(w/42,13,30),playerX=w*.5,from=Math.max(0,Math.floor(progress-playerX/xStep)-4),to=Math.min(rows.length-1,Math.ceil(progress+(w-playerX)/xStep)+4),top=22,bottom=h-58,center=(top+bottom)/2,scale=h*4.0,cur=rowAt(rows,progress),anchor=Math.log(Math.max(1,cur[5]));if(state.cameraLog==null||instant)state.cameraLog=anchor;else{const currentY=center-(anchor-state.cameraLog)*scale,upper=top+(bottom-top)*.30,lower=top+(bottom-top)*.70;let desired=state.cameraLog;if(currentY<upper)desired+=(upper-currentY)/scale;else if(currentY>lower)desired-=(currentY-lower)/scale;state.cameraLog=lerp(state.cameraLog,desired,clamp(dt*3.2,0,1));}return{w,h,xStep,playerX,from,to,top,bottom,toY:v=>center-(Math.log(Math.max(1,v))-state.cameraLog)*scale};}
async function startGame(){const rows=DATA[state.market].rows;if(!rows?.length)return;$('nickname').value=sanitizeName($('nickname').value);stopBgm();Object.assign(state,{running:false,started:false,progress:0,prevProgress:0,elapsed:0,lastTs:0,vy:0,pressing:false,cameraLog:null,eventUntil:0,lastEventKey:'',moveUntil:0,lastMoveKey:'',lastYear:rows[0][0].slice(0,4),trail:[]});ensureAudio();showScreen('game');resizeCanvas();const m=mapView(0,0,true);state.playerY=m.toY(rows[0][5]);drawFrame(0,baseSpeed(rows)*speedFactor(1));$('countdown').classList.remove('hidden');for(const n of ['3','2','1']){$('countdown').textContent=n;beep(n==='1'?680:460,.05,'square');await new Promise(r=>setTimeout(r,360));}$('countdown').textContent='GO';beep(880,.09,'square',.025);await new Promise(r=>setTimeout(r,170));$('countdown').classList.add('hidden');state.running=true;state.started=true;state.lastTs=performance.now();startBgm();state.raf=requestAnimationFrame(loop);}
function pressStart(e){e?.preventDefault?.();if(!state.running)return;state.pressing=true;const h=canvas._h||600;state.vy=Math.max(-h*.648,state.vy-h*.174);beep(590,.01,'square',.006)}function pressEnd(e){e?.preventDefault?.();state.pressing=false}canvas.addEventListener('pointerdown',e=>{try{canvas.setPointerCapture(e.pointerId)}catch{}pressStart(e)});canvas.addEventListener('pointerup',pressEnd);canvas.addEventListener('pointercancel',pressEnd);canvas.addEventListener('pointerleave',e=>{if(e.buttons===0)pressEnd(e)});window.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat){e.preventDefault();pressStart(e)}});window.addEventListener('keyup',e=>{if(e.code==='Space'){e.preventDefault();pressEnd(e)}});
function maybeEvent(){for(const e of DATA[state.market].events||[]){if(state.prevProgress<e.index&&state.progress>=e.index){const key=e.date+(e.titleEn||'');if(key===state.lastEventKey)continue;state.lastEventKey=key;state.eventUntil=performance.now()+3200;$('eventDate').textContent=`${eventKind(e.kind)} · ${formatFullDate(e.date)}`;$('eventTitle').textContent=state.lang==='ja'?e.titleJa:e.titleEn;$('eventComment').textContent=state.lang==='ja'?e.commentJa:e.commentEn;$('eventBanner').dataset.kind=e.kind||'market';$('eventBanner').classList.remove('hidden');playHistorySE(e.kind||'market');break;}}}
function maybeYear(rows){const idx=clamp(Math.floor(state.progress),0,rows.length-1),year=rows[idx][0].slice(0,4);if(state.lastYear&&year!==state.lastYear)playYearSE();state.lastYear=year;}
function maybeMove(){for(const m of DATA[state.market].moves||[]){if(state.prevProgress<m.index&&state.progress>=m.index){const key=m.date+m.pct;if(key===state.lastMoveKey)continue;state.lastMoveKey=key;state.moveUntil=performance.now()+2100;$('movePct').textContent=`${m.pct>0?'+':''}${m.pct.toFixed(2)}%`;$('moveDate').textContent=`${formatFullDate(m.date)} · ${fmtValue(m.close)}`;$('moveFlash').className=`move-flash ${m.pct>=0?'positive':'negative'}`;beep(m.pct>=0?860:120,.18,m.pct>=0?'square':'sawtooth',.022);break;}}}
function loop(ts){if(!state.running)return;const dt=clamp((ts-state.lastTs)/1000,0,.045);state.lastTs=ts;state.elapsed+=dt*1000;const rows=DATA[state.market].rows,speed=baseSpeed(rows)*speedFactor();state.prevProgress=state.progress;state.progress+=speed*dt;const h=canvas._h||620,acc=state.pressing?-h*.66:h*1.0032;state.vy+=acc*dt;state.vy*=Math.pow(.36,dt);state.vy=clamp(state.vy,-h*.7128,h*.66);state.playerY+=state.vy*dt;maybeYear(rows);maybeEvent();maybeMove();drawFrame(dt,speed);if(performance.now()>state.eventUntil)$('eventBanner').classList.add('hidden');if(performance.now()>state.moveUntil)$('moveFlash').classList.add('hidden');if(state.elapsed>800){const cur=rowAt(rows,state.progress),map=mapView(state.progress,0,false),d=dynBand(cur),uy=map.toY(d.upper),ly=map.toY(d.lower);if(state.playerY-PLAYER_R<=uy||state.playerY+PLAYER_R>=ly||state.playerY<-40||state.playerY>map.h+40)return endGame(false,'BAND OUT');}if(state.elapsed>=MAX_MS||state.progress>=rows.length-1){state.progress=rows.length-1;return endGame(true,'FULL RUN')}state.raf=requestAnimationFrame(loop);}
function drawCandle(x,row,toY,width){const o=toY(row[1]),hi=toY(row[2]),lo=toY(row[3]),c=toY(row[4]),up=row[4]>=row[1];ctx.strokeStyle=up?'rgba(96,242,154,.70)':'rgba(255,93,104,.70)';ctx.fillStyle=up?'rgba(96,242,154,.55)':'rgba(255,93,104,.55)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,hi);ctx.lineTo(x,lo);ctx.stroke();ctx.fillRect(x-width/2,Math.min(o,c),width,Math.max(1.5,Math.abs(c-o)));}
function drawFrame(dt=0,speed=1){if(!DATA?.[state.market])return;const rows=DATA[state.market].rows,map=mapView(state.progress,dt,false),{w,h,xStep,playerX,from,to,toY}=map,bf=bandFactor(),X=i=>playerX+(i-state.progress)*xStep;ctx.clearRect(0,0,w,h);ctx.fillStyle='#06090b';ctx.fillRect(0,0,w,h);const shift=(state.elapsed/7)%95;ctx.strokeStyle='rgba(255,255,255,.03)';for(let y=60;y<h-58;y+=64){for(let x=-100+shift;x<w;x+=170){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+54+stageNo()*.18,y);ctx.stroke();}}ctx.strokeStyle='#11181d';for(let i=1;i<5;i++){const y=22+(h-80)*i/5;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}
ctx.beginPath();let first=true;for(let i=from;i<=to;i++){const d=dynBand(rows[i],bf),x=X(i),y=toY(d.upper);first?(ctx.moveTo(x,y),first=false):ctx.lineTo(x,y)}for(let i=to;i>=from;i--){const d=dynBand(rows[i],bf);ctx.lineTo(X(i),toY(d.lower))}ctx.closePath();ctx.fillStyle='rgba(103,243,157,.065)';ctx.fill();const cw=Math.max(3,xStep*.52);for(let i=from;i<=to;i++)drawCandle(X(i),rows[i],toY,cw);
for(const side of ['upper','lower']){ctx.beginPath();first=true;for(let i=from;i<=to;i++){const d=dynBand(rows[i],bf),x=X(i),y=toY(d[side]);first?(ctx.moveTo(x,y),first=false):ctx.lineTo(x,y)}ctx.strokeStyle='rgba(103,243,157,.85)';ctx.lineWidth=2;ctx.stroke()}ctx.beginPath();first=true;for(let i=from;i<=to;i++){const x=X(i),y=toY(rows[i][5]);first?(ctx.moveTo(x,y),first=false):ctx.lineTo(x,y)}ctx.setLineDash([5,6]);ctx.strokeStyle='rgba(220,228,233,.24)';ctx.lineWidth=1;ctx.stroke();ctx.setLineDash([]);
for(const e of DATA[state.market].events||[]){if(e.index<from||e.index>to)continue;const x=X(e.index);ctx.strokeStyle=eventColor(e.kind,.28);ctx.beginPath();ctx.moveTo(x,24);ctx.lineTo(x,h-58);ctx.stroke();ctx.save();ctx.translate(x+5,42);ctx.rotate(-Math.PI/2);ctx.fillStyle=eventColor(e.kind,.82);ctx.font='950 17px system-ui';ctx.textAlign='right';ctx.fillText(state.lang==='ja'?e.titleJa:e.titleEn,0,0);ctx.restore();}
for(const m of DATA[state.market].moves||[]){if(m.index<from||m.index>to)continue;const x=X(m.index),y=clamp(toY(rows[m.index][4]),64,h-126),up=m.pct>=0;ctx.fillStyle=up?'rgba(96,242,154,.98)':'rgba(255,93,104,.98)';ctx.font='1000 34px system-ui';ctx.textAlign='center';ctx.fillText(`${m.pct>0?'+':''}${m.pct.toFixed(2)}%`,x,y-16);ctx.font='900 13px system-ui';ctx.fillText(formatFullDate(m.date),x,y);}
ctx.fillStyle='#080c0f';ctx.fillRect(0,h-68,w,68);ctx.strokeStyle='#1a2228';ctx.beginPath();ctx.moveTo(0,h-68);ctx.lineTo(w,h-68);ctx.stroke();let lastX=-999,lastYM='';ctx.font='900 14px system-ui';ctx.textAlign='center';for(let i=from;i<=to;i++){const ym=rows[i][0].slice(0,7);if(ym!==lastYM){lastYM=ym;const x=X(i);if(x-lastX>70){lastX=x;ctx.fillStyle='#69757f';ctx.fillText(state.lang==='ja'?ym.replace('-','/'):ym,x,h-23);ctx.strokeStyle='#202a31';ctx.beginPath();ctx.moveTo(x,h-68);ctx.lineTo(x,h-55);ctx.stroke();}}}
ctx.strokeStyle='rgba(255,255,255,.12)';ctx.beginPath();ctx.moveTo(playerX,22);ctx.lineTo(playerX,h-68);ctx.stroke();state.trail.unshift(state.playerY);if(state.trail.length>24)state.trail.length=24;for(let i=state.trail.length-1;i>=1;i--){const a=1-i/state.trail.length;ctx.strokeStyle=`rgba(103,243,157,${a*.20})`;ctx.lineWidth=Math.max(1,5*a);ctx.beginPath();ctx.moveTo(playerX-i*6.3,state.trail[i]);ctx.lineTo(playerX-(i-1)*6.3,state.trail[i-1]);ctx.stroke();}const py=state.started?state.playerY:toY(rows[0][5]);ctx.shadowColor='rgba(103,243,157,.9)';ctx.shadowBlur=24;ctx.fillStyle='#67f39d';ctx.beginPath();ctx.arc(playerX,py,PLAYER_R,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#eafff0';ctx.beginPath();ctx.moveTo(playerX+11,py);ctx.lineTo(playerX+2,py-4.5);ctx.lineTo(playerX+2,py+4.5);ctx.closePath();ctx.fill();const cur=rowAt(rows,state.progress),d=dynBand(cur);ctx.font='950 20px system-ui';ctx.textAlign='left';ctx.fillStyle='#6f7d86';const uy=toY(d.upper),ly=toY(d.lower);const sig=effectiveSigma(),sigText=sig>=2?sig.toFixed(1):sig.toFixed(2);if(uy>10&&uy<h-74)ctx.fillText(`+${sigText}σ`,8,uy-5);if(ly>10&&ly<h-74)ctx.fillText(`−${sigText}σ`,8,ly+13);ctx.textAlign='center';ctx.fillStyle='#dce3e7';ctx.font='950 20px system-ui';ctx.fillText(formatDate(cur[0]),playerX,h-39);$('hudMarket').textContent=`${marketLabel()} / ${modeLabel()}`;$('hudDate').textContent=formatHUDDate(cur[0]);$('hudValue').textContent=fmtValue(cur[4]);$('hudLevel').textContent=String(stageNo()).padStart(3,'0');$('hudTime').textContent=fmtTime(state.elapsed);$('progressBar').style.width=`${clamp(state.progress/(rows.length-1)*100,0,100)}%`;}
async function endGame(clear,title){if(!state.running)return;state.running=false;state.pressing=false;cancelAnimationFrame(state.raf);stopBgm();$('eventBanner').classList.add('hidden');$('moveFlash').classList.add('hidden');beep(clear?930:110,clear?.2:.3,clear?'sine':'sawtooth',.03);const rows=DATA[state.market].rows,idx=clamp(Math.floor(state.progress),0,rows.length-1),r=rows[idx],progress=clamp(idx/(rows.length-1)*100,0,100),result={market:rankingKey(),nickname:sanitizeName($('nickname').value),scoreIndex:idx,resultDate:r[0],indexValue:r[4],elapsedMs:Math.min(Math.floor(state.elapsed),MAX_MS),progress:Number(progress.toFixed(3)),clear};saveLocalScore(result);await submitScore(result);$('resultOverline').textContent=clear?t('complete'):t('ended');$('resultTitle').textContent=title;$('resultTitle').style.color=clear?'var(--accent)':'var(--danger)';$('resultDate').textContent=formatDate(r[0]);$('resultValue').textContent=fmtValue(r[4]);$('resultProgress').textContent=`${progress.toFixed(1)}%`;$('resultTime').textContent=fmtTime(Math.min(state.elapsed,MAX_MS));$('resultBest').textContent=`${getLocalBest(rankingKey()).toFixed(1)}%`;$('rankingTitle').textContent=`${marketLabel()} / ${modeLabel()} TOP 10`;showScreen('result');loadRanking('resultRanking',rankingKey());}
$('startBtn').addEventListener('click',startGame);$('retryBtn').addEventListener('click',startGame);$('homeBtn').addEventListener('click',()=>{showScreen('home');loadRanking('homeRanking',rankingKey())});$('refreshHomeRanking').addEventListener('click',()=>loadRanking('homeRanking',rankingKey()));$('refreshResultRanking').addEventListener('click',()=>loadRanking('resultRanking',rankingKey()));
const LS_KEY='bollinger-run-scores-v4-modes';function localScores(){try{return JSON.parse(localStorage.getItem(LS_KEY)||'[]')}catch{return[]}}function saveLocalScore(s){try{const all=localScores();all.push({...s,createdAt:Date.now()});all.sort((a,b)=>b.scoreIndex-a.scoreIndex||b.elapsedMs-a.elapsedMs);localStorage.setItem(LS_KEY,JSON.stringify(all.slice(0,100)));return true}catch{return false}}function getLocalBest(m){const a=localScores().filter(x=>x.market===m);return a.length?Math.max(...a.map(x=>Number(x.progress)||0)):0}async function submitScore(){return false}async function getScores(m){const mp=new Map();for(const s of localScores().filter(x=>x.market===m)){const old=mp.get(s.nickname);if(!old||s.scoreIndex>old.scoreIndex)mp.set(s.nickname,s)}return{scores:[...mp.values()].sort((a,b)=>b.scoreIndex-a.scoreIndex||b.elapsedMs-a.elapsedMs).slice(0,10),global:false}}function escapeHTML(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}async function loadRanking(targetId,m){const el=$(targetId);if(!el)return;el.innerHTML=`<p class="empty">${t('loading')}</p>`;const{scores,global}=await getScores(m);if(!scores.length){el.innerHTML=`<p class="empty">${t('empty')}</p>`;return}el.innerHTML=scores.slice(0,10).map((s,i)=>`<div class="rank-row"><span class="rank">${String(i+1).padStart(2,'0')}</span><span class="name">${escapeHTML(s.nickname||t('anon'))}</span><span class="where">${formatDate(s.resultDate||s.result_date||DATA.nikkei.rows[0][0])}</span><span class="score">${Number(s.progress).toFixed(1)}%</span></div>`).join('')+`<p class="empty">${global?t('global'):t('local')}</p>`;}
window.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.running)state.lastTs=performance.now()});resizeCanvas();applyLanguage();loadRanking('homeRanking',rankingKey());
})();
